### ISSUE TITLE
The second example in the README has an error

### ISSUE THREAD

**Issue by sweetbbak** [go-shiori/go-readability#39]
```
		article, err := readability.FromReader(resp.Body, url)
		if err != nil {
			log.Fatalf("failed to parse %s: %v\n", url, err)
		}
```
the error:
Cannot use url (variable type string) as *url.URL in argument to readability.FromReader

**Comment by fmartingr** [comment]
This would be probably solved if you use:

```go

parsedURL, err := url.Parse("my URL")
if err != nil {
  log.Fatalf("error parsing url")
}

article, err := readability.FromReader(resp.Body, parsedURL)
```

Can you check if this works for you? If it does, could you submit a PR updating the README?

**Comment by sweetbbak** [comment]
Thanks for the help. I sent a PR with the updated changes.
