### ISSUE TITLE
Articles with bad dates generates error in stdout

### ISSUE THREAD

**Issue by jvegaseg** [go-shiori/go-readability#49]
It is very annoying.

Affected line is in function getParsedDate:

`fmt.Printf("Failed to parse date \"%s\"\n", dateStr)`

Could it be avoided?

Regards

**Comment by fmartingr** [comment]
Hey #48 removed this log line, but right now it is the only way we know of time parsing failures easily in the logs. I've requested to add it back, but it seems that some of you think it should be gone. 

I'm all in for it to be gone if we refactor the `getParsedDate` function to return an `error` when it fails to parse the datetime, ignoring it in the consumer if it's not needed. That's the way it should be done.

cc: @vlanse @rmarku
