### ISSUE TITLE
Missing whitespace

### ISSUE THREAD

**Issue by sklinkert** [go-shiori/go-readability#6]
First of all, thanks for doing this. I really appreciate this library.

Recently I noticed an annoying bug. If the text contains hyperlinks, the HTML tags get removed but unfortunately there is a whitespace missing between the parsed words.

For example, the first sentence of the parsed text from https://www.thebalance.com/gold-etf-what-you-need-to-know-1214748 should be:

>A gold ETF, or exchange-traded fund, is a commodity ETF that consists of only one principal asset

But is:

>A gold ETF, or exchange-traded fund, is acommodity ETFthat consists of only one principal asset

I've tried to locate the cause for this behavior but I still have no clue. 

-Simon

**Comment by RadhiFadlillah** [comment]
It should have been fixed per latest commit.
